# Generated by Django 2.0 on 2019-01-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentasporcobrar',
            name='saldo_cc',
            field=models.FloatField(null=True),
        ),
    ]
