# Generated by Django 2.0 on 2018-11-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='direccion',
            field=models.CharField(max_length=500),
        ),
    ]
