# Generated by Django 2.0 on 2018-11-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembro', '0002_auto_20181104_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='medalla',
            field=models.ManyToManyField(to='miembro.Medalla'),
        ),
    ]
