# Generated by Django 2.0 on 2018-11-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembro', '0003_miembro_medalla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='foto_m',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
    ]
