# Generated by Django 2.0 on 2018-11-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembro', '0004_auto_20181104_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='foto_m',
            field=models.ImageField(blank=True, upload_to='static/img'),
        ),
    ]
