# Generated by Django 2.0 on 2018-11-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembro', '0005_auto_20181104_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='foto_m',
            field=models.FileField(blank=True, upload_to='static/img'),
        ),
    ]
