# Generated by Django 2.0 on 2018-11-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembro', '0008_remove_miembro_anio_ingreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hermandad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_hermandad', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='miembro',
            name='hermandad',
            field=models.ManyToManyField(to='miembro.Hermandad'),
        ),
    ]
