# Generated by Django 2.0 on 2018-11-05 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miembro', '0009_auto_20181105_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miembro',
            name='hermandad',
        ),
        migrations.AddField(
            model_name='miembro',
            name='hermandad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miembro.Hermandad'),
        ),
    ]
