# Generated by Django 2.0 on 2018-11-07 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_periodo', models.DateField()),
                ('final_periodo', models.DateField()),
                ('estado_periodo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoAnualDirectivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_periodo_anual', models.DateField()),
                ('final_periodo_anual', models.DateField()),
                ('nombre_periodo', models.CharField(max_length=50)),
                ('estado_periodo_anual', models.BooleanField()),
                ('periodo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transaccion.Periodo')),
            ],
        ),
        migrations.CreateModel(
            name='Tesoreria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tesoreria', models.CharField(max_length=50)),
                ('saldo_tesoreria', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_transaccion', models.DateField()),
                ('concepto_transaccion', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('monto_transaccion', models.FloatField()),
                ('tesoreria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transaccion.Tesoreria')),
            ],
        ),
        migrations.AddField(
            model_name='periodo',
            name='transacciones',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transaccion.Transaccion'),
        ),
    ]
