# Generated by Django 2.0 on 2018-12-12 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miembro', '0001_initial'),
        ('transaccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoDirectivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cargo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Directivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaccion.CargoDirectivo')),
                ('miembro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miembro.Miembro')),
            ],
        ),
        migrations.AddField(
            model_name='periodoanualdirectivo',
            name='directiva_asignada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='directivo',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaccion.PeriodoAnualDirectivo'),
        ),
    ]
