# Generated by Django 2.0 on 2019-01-17 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miembro', '0002_cuentasporcobrar_saldo_cc'),
        ('transaccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoDirectivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cargo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Directivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=False)),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaccion.CargoDirectivo')),
                ('miembro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miembro.Miembro')),
            ],
        ),
        migrations.RemoveField(
            model_name='periodo',
            name='transacciones',
        ),
        migrations.RemoveField(
            model_name='periodoanualdirectivo',
            name='periodo',
        ),
        migrations.AddField(
            model_name='periodo',
            name='periodo_anual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transaccion.PeriodoAnualDirectivo'),
        ),
        migrations.AddField(
            model_name='periodoanualdirectivo',
            name='directiva_asignada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='periodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transaccion.Periodo'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='saldo_transaccion',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='directivo',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaccion.PeriodoAnualDirectivo'),
        ),
    ]
