# Generated by Django 2.0 on 2018-12-18 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0003_directivo_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodo',
            name='transacciones',
        ),
        migrations.RemoveField(
            model_name='periodoanualdirectivo',
            name='periodo',
        ),
        migrations.AddField(
            model_name='periodo',
            name='periodo_anual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transaccion.PeriodoAnualDirectivo'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='periodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transaccion.Periodo'),
        ),
    ]
