# Generated by Django 2.0 on 2018-11-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen_articulo',
            field=models.ImageField(blank=True, upload_to='static/img'),
        ),
    ]
