# Generated by Django 2.0 on 2019-01-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='monto_total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='venta',
            name='precio_venta_unitario',
            field=models.IntegerField(),
        ),
    ]
