# Generated by Django 2.0 on 2018-11-06 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_auto_20181104_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen_articulo',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
    ]
